feature {
  name: "age_xf"
  type: FLOAT
  presence {
    min_fraction: 1.0
  }
  shape {
  }
}
feature {
  name: "capital-gain_xf"
  type: FLOAT
  presence {
    min_fraction: 1.0
  }
  shape {
  }
}
feature {
  name: "capital-loss_xf"
  type: FLOAT
  presence {
    min_fraction: 1.0
  }
  shape {
  }
}
feature {
  name: "education_xf"
  type: INT
  int_domain {
    min: 0
    max: 16
    is_categorical: true
  }
  presence {
    min_fraction: 1.0
  }
  shape {
  }
}
feature {
  name: "educational-num_xf"
  type: FLOAT
  presence {
    min_fraction: 1.0
  }
  shape {
  }
}
feature {
  name: "fnlwgt_xf"
  type: FLOAT
  presence {
    min_fraction: 1.0
  }
  shape {
  }
}
feature {
  name: "gender_xf"
  type: INT
  int_domain {
    min: 0
    max: 2
    is_categorical: true
  }
  presence {
    min_fraction: 1.0
  }
  shape {
  }
}
feature {
  name: "hours-per-week_xf"
  type: FLOAT
  presence {
    min_fraction: 1.0
  }
  shape {
  }
}
feature {
  name: "income_xf"
  type: INT
  presence {
    min_fraction: 1.0
  }
  shape {
  }
}
feature {
  name: "marital-status_xf"
  type: INT
  int_domain {
    min: 0
    max: 7
    is_categorical: true
  }
  presence {
    min_fraction: 1.0
  }
  shape {
  }
}
feature {
  name: "native-country_xf"
  type: INT
  int_domain {
    min: 0
    max: 42
    is_categorical: true
  }
  presence {
    min_fraction: 1.0
  }
  shape {
  }
}
feature {
  name: "occupation_xf"
  type: INT
  int_domain {
    min: 0
    max: 15
    is_categorical: true
  }
  presence {
    min_fraction: 1.0
  }
  shape {
  }
}
feature {
  name: "race_xf"
  type: INT
  int_domain {
    min: 0
    max: 5
    is_categorical: true
  }
  presence {
    min_fraction: 1.0
  }
  shape {
  }
}
feature {
  name: "relationship_xf"
  type: INT
  int_domain {
    min: 0
    max: 6
    is_categorical: true
  }
  presence {
    min_fraction: 1.0
  }
  shape {
  }
}
feature {
  name: "workclass_xf"
  type: INT
  int_domain {
    min: 0
    max: 9
    is_categorical: true
  }
  presence {
    min_fraction: 1.0
  }
  shape {
  }
}
